"""empty message

Revision ID: 385e95bb0cb1
Revises: 97b2cbbdabb6
Create Date: 2022-04-25 17:51:40.000437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '385e95bb0cb1'
down_revision = '97b2cbbdabb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url_shortner', 'note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_shortner', sa.Column('note', mysql.VARCHAR(length=512), nullable=True))
    # ### end Alembic commands ###
