"""empty message

Revision ID: d2fa46fe573c
Revises: d924e59a65db
Create Date: 2022-04-25 17:50:52.040074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2fa46fe573c'
down_revision = 'd924e59a65db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url_shortner', 'note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_shortner', sa.Column('note', mysql.VARCHAR(length=512), nullable=True))
    # ### end Alembic commands ###
