"""empty message

Revision ID: d924e59a65db
Revises: 
Create Date: 2022-04-25 17:50:29.831225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd924e59a65db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_shortner', sa.Column('note', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url_shortner', 'note')
    # ### end Alembic commands ###
